#!/bin/sh
set -eu

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

expand_path() {
    echo "$1" | sed "s|^~|$HOME|"
}

sync_item() {
    src="$1"
    dst="$REPO_DIR/$2"

    if [ ! -e "$src" ]; then
        return
    fi

    if [ -d "$src" ]; then
        mkdir -p "$dst"
        rsync -a --delete "$src" "$dst"
        echo "DIR:  $2"
    else
        mkdir -p "$(dirname "$dst")"
        cp -a "$src" "$dst"
        echo "FILE: $2"
    fi
}

# --- Global config (mystrap stow layout, not standard Claude structure) ---

GLOBAL_SRC=~/dev/mystrap/dotfiles/claude/.claude
GLOBAL_SRC=$(expand_path "$GLOBAL_SRC")

sync_item "$GLOBAL_SRC/CLAUDE.md"           "global/CLAUDE.md"
sync_item "$GLOBAL_SRC/settings.json"       "global/settings.json"
sync_item "$GLOBAL_SRC/settings.local.json" "global/settings.local.json"
sync_item "$GLOBAL_SRC/statusline.sh"       "global/statusline.sh"
sync_item "$GLOBAL_SRC/agents/"             "global/agents/"
sync_item "$GLOBAL_SRC/hooks/"              "global/hooks/"
sync_item "$GLOBAL_SRC/skills/"             "global/skills/"

# --- Projects (auto-discover Claude config patterns) ---

sync_project() {
    name="$1"
    src=$(expand_path "$2")

    # Top-level CLAUDE.md
    sync_item "$src/CLAUDE.md" "projects/$name/CLAUDE.md"

    # .claude/ subdirectories
    for dir in commands hooks agents; do
        sync_item "$src/.claude/$dir/" "projects/$name/$dir/"
    done

    # .claude/settings.local.json
    sync_item "$src/.claude/settings.local.json" "projects/$name/settings.local.json"

    # Nested CLAUDE.md files (one level deep)
    if [ -d "$src" ]; then
        for child in "$src"/*/; do
            child_name=$(basename "$child")
            if [ -f "$child/CLAUDE.md" ]; then
                sync_item "$child/CLAUDE.md" "projects/$name/$child_name/CLAUDE.md"
            fi
        done
    fi
}

echo "Syncing files to $REPO_DIR..."

sync_project "planning"    "~/Cloud/janvv/life/planning"
sync_project "vault-root"  "~/Cloud/janvv/life"
sync_project "docs"        "~/Cloud/janvv/life/docs"
sync_project "website"     "~/dev/janvv.nl"

# --- llm-context files (skip private ones) ---

LLM_CTX_SRC=$(expand_path "~/Cloud/janvv/life/llm-context")
LLM_CTX_DST="$REPO_DIR/llm-context"

mkdir -p "$LLM_CTX_DST"
for f in "$LLM_CTX_SRC"/*.md; do
    name=$(basename "$f")
    case "$name" in
        personal.md|church.md|google-api.md) continue ;;
    esac
    cp -a "$f" "$LLM_CTX_DST/$name"
    echo "FILE: llm-context/$name"
done
# Remove files that were previously synced but are now excluded
for f in "$LLM_CTX_DST"/*.md; do
    name=$(basename "$f")
    if [ ! -f "$LLM_CTX_SRC/$name" ]; then
        rm "$f"
    fi
done

# --- docs/ structure tree (filenames only, no content) ---

DOCS_SRC=$(expand_path "~/Cloud/janvv/life/docs")
DOCS_TREE="$REPO_DIR/docs-structure.md"

{
    echo "# docs/ structure"
    echo ""
    echo "File tree of the documentation layer. These files are not included in the repo"
    echo "because they contain private details (service configs, personal docs). This listing"
    echo "shows the scope and organization."
    echo ""
    echo "Generated by sync.sh on $(date +%Y-%m-%d)."
    echo ""
    echo '```'
    (cd "$DOCS_SRC" && find . -name '*.md' | sort | sed 's|^\./||')
    echo '```'
} > "$DOCS_TREE"
echo "FILE: docs-structure.md"

echo "Done. Run 'git diff' to review changes."
